theme: jekyll-theme-cayman
title: [Bamberg-Halle-Jena-Leipzig Doctoral Workshop]
description: [The aim of this workshop is to bring together junior researchers from the cooperating chairs at the Universities of Bamberg, Halle, Jena and Leipzig who do work in applied microeconomics and empirical econometrics.]


